INSERT INTO Turmas (sigla, docente, ativo) VALUES
('M1A', 'WILLIAM', 1),
('M3A', 'FABIO', 1),
('M3B', 'EPAMINONDAS', 1),
('M1C', 'ROGÉRIO POLETO', 1),
('M3D', 'WALDEMAR', 1),
('M1F', 'ALCINDO', 1),
('M1I', 'BRUNA', 1),
('M1IA', 'LUCAS / GABRIELA', 1),
('M1H', 'IZAIAS', 1),
('T1A', 'LUCIANO', 1),
('T1B', 'DENIS', 1),
('T1C', 'ROGÉRIO POLETO', 1),
('T1D', 'WALDEMAR', 1),
('T1IA', 'MARILIA', 1),
('T1I', 'LUCAS / JOSÉ AUGUSTO', 1),
('T3FA', 'ALEX', 1),
('T2FC', 'FERNANDO', 1),
('T3F', 'VITOR', 1),
('T1FB', 'BRUNO', 1),
('I1F', 'SERGIO', 1),
('I1FA', 'ALEX PENTEADO', 1),
('I1HS', 'MAYCON', 1),
('I1HSB', 'RICARDO', 1),
('I1E', 'JOÃO FLAVIO', 1),
('I2HS', 'ANA', 1),
('N1I', 'MARILIA', 1),
('N3F', 'EVANDRO', 1);
